-- MySQL Script generated by MySQL Workbench
-- Wed Nov  2 21:13:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Gym
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Gym
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Gym` DEFAULT CHARACTER SET utf8 ;
USE `Gym` ;

-- -----------------------------------------------------
-- Table `Gym`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gym`.`Rooms` (
  `idRooms` INT NOT NULL AUTO_INCREMENT,
  `Number` INT NOT NULL,
  PRIMARY KEY (`idRooms`, `Number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gym`.`Trainers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gym`.`Trainers` (
  `idTrainers` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTrainers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gym`.`Workout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gym`.`Workout` (
  `idWorkout` INT NOT NULL AUTO_INCREMENT,
  `Rooms_idRooms` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Duration` INT NOT NULL,
  `Trainers_idTrainers` INT NOT NULL,
  PRIMARY KEY (`idWorkout`, `Rooms_idRooms`),
  INDEX `fk_Workout_Rooms1_idx` (`Rooms_idRooms` ASC) VISIBLE,
  INDEX `fk_Workout_Trainers1_idx` (`Trainers_idTrainers` ASC) VISIBLE,
  CONSTRAINT `fk_Workout_Rooms1`
    FOREIGN KEY (`Rooms_idRooms`)
    REFERENCES `Gym`.`Rooms` (`idRooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Workout_Trainers1`
    FOREIGN KEY (`Trainers_idTrainers`)
    REFERENCES `Gym`.`Trainers` (`idTrainers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gym`.`Members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gym`.`Members` (
  `idMembers` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMembers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gym`.`Stuff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gym`.`Stuff` (
  `idStuff` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Rooms_idRooms` INT NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStuff`, `Rooms_idRooms`),
  INDEX `fk_Stuff_Rooms1_idx` (`Rooms_idRooms` ASC) VISIBLE,
  CONSTRAINT `fk_Stuff_Rooms1`
    FOREIGN KEY (`Rooms_idRooms`)
    REFERENCES `Gym`.`Rooms` (`idRooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gym`.`Members_has_Workout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gym`.`Members_has_Workout` (
  `Members_idMembers` INT NOT NULL,
  `Workout_idWorkout` INT NOT NULL,
  `Member Name` VARCHAR(45) NOT NULL,
  `Workout Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Members_idMembers`, `Workout_idWorkout`),
  INDEX `fk_Members_has_Workout_Workout1_idx` (`Workout_idWorkout` ASC) VISIBLE,
  INDEX `fk_Members_has_Workout_Members1_idx` (`Members_idMembers` ASC) VISIBLE,
  CONSTRAINT `fk_Members_has_Workout_Members1`
    FOREIGN KEY (`Members_idMembers`)
    REFERENCES `Gym`.`Members` (`idMembers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Members_has_Workout_Workout1`
    FOREIGN KEY (`Workout_idWorkout`)
    REFERENCES `Gym`.`Workout` (`idWorkout`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
